name = "frienda-circle-proxy"
main = "src/index.js"
compatibility_date = "2026-08-04"

[browser]
binding = "MYBROWSER"

[durable_objects]
bindings = [
  { name = "RATE_LIMIT", class_name = "RateLimit" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimit"]
